version: '3.8'

services:
  minecraft:
    container_name: paper
    image: evilcious/paper-server:${{ steps.tag_version.outputs.new_tag }}
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./plugins:/plugins
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      # More aggressive settings for demo purposes
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
      SPIGET_RESOURCES: 34315,3836
    restart: unless-stopped

volumes:
  data: {}
