name: Checkout, Tag/release, Build, Push
# This workflow represents a set of basic End-to-End tests
on:
#  push:
#    branches:
#      - 'master'
#  pull_request:
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GitHub Tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
  reporting:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - name: Metrics embed
      uses: lowlighter/metrics@v3.34
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Actions for Discord
    #   uses: Ilshidur/action-discord@0.3.2