name: Checkout, Tag/release, Build, Push
# This workflow represents a set of basic End-to-End tests
on:
#  push:
#    branches:
#      - 'master'
#  pull_request:
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag/Release on Push Action
      uses: rymndhng/release-on-push-action@v0.28.0
      with:
        github_token: ${{ secrets.PAT }}
        bump_version_scheme: minor
#    - name: Docker Lint
#      uses: luke142367/Docker-Lint-Action@v1.1.1
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
  reporting:
    runs-on: ubuntu-latest
    steps:
    - name: Metrics embed
      uses: lowlighter/metrics@v3.34
    - name: Actions for Discord
      uses: Ilshidur/action-discord@0.3.2